spring:
  application:
    name: LedgerService
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization:
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: zing_consumer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        enable.idempotence: true

logging:
  file:
    name: zing.log